# Generated by Django 5.1.3 on 2024-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.TextField(unique=True),
        ),
    ]
