# Generated by Django 5.1.3 on 2024-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
